name = "COTTAGE"
author = "dummies"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b8d80bc1901a37c6dc787beb8776b8745f2cdfb5c0f1e1c8197299d68824afa"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
