name = "COTTAGE"
author = "dummies"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8527bea74fdae65e10e6ccdd4a49d4f56ab3caacc681836d49d1d90ab7e78f5"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
