name = "COTTAGE"
author = "dummies"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8e3a8e1bc168dca31df0fbb315c0436ee3e38cf67fd37351a675d38352a9a33"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
